ci:
  autofix_prs: false
  skip: [docker-compose-check]

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        language_version: python3
        args:
        # TODO: replace this with ruff to bring all config into pyproject.toml
          - --config=.flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args: 
          - "--autofix"
          - "--no-sort-keys"

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args:
          - --settings-path=pyproject.toml

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: 
          - --toml=pyproject.toml

  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
        args:
          - --config-file=pyproject.toml
