version: "3.8"

services:
  api:
    image: "neurobagel/api:${NB_API_TAG:-latest}"
    ports:
      - "8000:8000"
    environment:
      NB_GRAPH_USERNAME: ${NB_GRAPH_USERNAME}
      NB_GRAPH_PASSWORD: ${NB_GRAPH_PASSWORD}
      NB_GRAPH_ADDRESS: ${NB_GRAPH_ADDRESS:-graph}
      NB_GRAPH_DB: ${NB_GRAPH_DB:-test_data}
      NB_RETURN_AGG: ${NB_RETURN_AGG:-true}
  graph:
    image: "ontotext/graphdb:${STARDOG_TAG:-10.2.4}"
    volumes:
      - "${STARDOG_ROOT:-~/stardog-home}:/opt/graphdb/home"
    ports:
      - "5820:7200"
