version: "3.8"

services:
  api:
    image: "neurobagel/api:${NB_API_TAG:-latest}"
    ports:
      - "${NB_API_PORT_HOST:-8000}:${NB_API_PORT:-8000}"
    environment:
      NB_GRAPH_USERNAME: ${NB_GRAPH_USERNAME}
      NB_GRAPH_PASSWORD: ${NB_GRAPH_PASSWORD}
      NB_GRAPH_ADDRESS: ${NB_GRAPH_ADDRESS:-graph}
      NB_GRAPH_PORT_HOST: ${NB_GRAPH_PORT_HOST:-5820}
      NB_GRAPH_DB: ${NB_GRAPH_DB:-test_data/query}
      NB_RETURN_AGG: ${NB_RETURN_AGG:-true}
      NB_API_PORT: ${NB_API_PORT:-8000}
      NB_API_ALLOWED_ORIGINS: ${NB_API_ALLOWED_ORIGINS}
  graph:
    image: "${NB_GRAPH_IMG:-stardog/stardog:8.2.2-java11-preview}"
    volumes:
      - "${NB_GRAPH_ROOT_HOST:-~/stardog-home}:${NB_GRAPH_ROOT_CONT:-/var/opt/stardog}"
    ports:
      - "${NB_GRAPH_PORT_HOST:-5820}:${NB_GRAPH_PORT:-5820}"
  query:
    image: "neurobagel/query_tool:${NB_QUERY_TAG:-latest}"
    ports:
      - "${NB_QUERY_PORT_HOST:-3000}:3000"
    environment:
      API_QUERY_URL: "${API_QUERY_URL:-http://localhost:8000/}"
