"""CRUD functions called by path operations."""
import os

import httpx
from fastapi import HTTPException

from . import utility as util


async def get(
    age_min: float,
    age_max: float,
    sex: str,
    diagnosis: str,
    is_control: bool,
    image_modal: str,
):
    """
    Makes a POST request to Stardog API using httpx where the payload is a SPARQL query generated by the create_query function.

    Parameters
    ----------
    age_min : float
        Minimum age of subject.
    age_max : float
        Maximum age of subject.
    sex : str
        Sex of subject.
    diagnosis : str
        Subject diagnosis.
    is_control : bool
        Whether or not subject is a control.
    image_modal : str
        Imaging modality of subject scans.

    Returns
    -------
    httpx.response
        Response of the POST request.

    """
    response = httpx.post(
        url=util.QUERY_URL,
        content=util.create_query(
            age=(age_min, age_max),
            sex=sex,
            diagnosis=diagnosis,
            is_control=is_control,
            image_modal=image_modal,
        ),
        headers=util.QUERY_HEADER,
        auth=httpx.BasicAuth(
            os.environ.get("USER"), os.environ.get("PASSWORD")
        ),
    )

    if not response.is_success:
        raise HTTPException(
            status_code=response.status_code,
            detail=f"{response.reason_phrase}: {response.text}",
        )

    results = response.json()

    return [
        {k: v["value"] for k, v in res.items()}
        for res in results["results"]["bindings"]
    ]
