"""CRUD functions called by path operations."""
from . import utility as util
import os
import httpx


async def get(sex: str):
    """
    Makes a POST request to Stardog API using httpx where the payload is a SPARQL query generated by the create_query function.

    Parameters
    ----------
    sex : str
        Subjects' sex.

    Returns
    -------
    httpx.response
        Response of the POST request.

    """
    response = httpx.post(
        url=util.QUERY_URL,
        content=util.create_query(sex=sex),
        headers=util.QUERY_HEADER,
        auth=httpx.BasicAuth(
            os.environ.get("USER"), os.environ.get("PASSWORD")
        ),
    )

    return response
