name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Launch test graph
      run: docker compose up -d test_graph export_datasets_metadata

    - name: Wait for graph setup
      run: |
        timeout=120
        elapsed=0

        until docker logs api-test_graph-1 2>&1 | grep -q "FINISHED UPLOADING DATA"; do
          if [ "$elapsed" -ge "$timeout" ]; then
            echo "Timed out waiting for graph setup"
            docker logs api-test_graph-1
            exit 1
          fi

          sleep 1
          elapsed=$((elapsed + 1))
        done

    - name: Debug containers and test graph
      run: |
        echo "=== All running and stopped containers ==="
        docker ps -a

        echo "=== Test graph logs ==="
        docker logs api-test_graph-1

        echo "=== Test graph data directory contents ==="
        ls -l ./test_graph_data

    - name: Set up Python 3.10 with uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Test with pytest
      run: |
        uv run pytest -m "integration or not integration" --cov --cov-branch --cov-report=xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
